// <auto-generated />
using AssetTracking_2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTracking_2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220601161944_SeedingAssetItem_Currency")]
    partial class SeedingAssetItem_Currency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssetTracking_2.AssetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EndOfLife")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PurchaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCountry");

                    b.ToTable("assetitems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "HP",
                            CurrencyCountry = "Spain",
                            EndOfLife = 20220601,
                            Model = "Elitebook",
                            Price = 1423.0,
                            PurchaseDate = 20190601,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HP",
                            CurrencyCountry = "Denmark",
                            EndOfLife = 20230526,
                            Model = "Elitebook",
                            Price = 588.0,
                            PurchaseDate = 20200526,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            CurrencyCountry = "Sweden",
                            EndOfLife = 20230316,
                            Model = "Elitebook",
                            Price = 588.0,
                            PurchaseDate = 20200316,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Asus",
                            CurrencyCountry = "Spain",
                            EndOfLife = 20220821,
                            Model = "W234",
                            Price = 1200.0,
                            PurchaseDate = 20190821,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            CurrencyCountry = "USA",
                            EndOfLife = 20200421,
                            Model = "Yoga 730",
                            Price = 1035.0,
                            PurchaseDate = 20170421,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Lenovo",
                            CurrencyCountry = "USA",
                            EndOfLife = 20220521,
                            Model = "Yoga 530",
                            Price = 835.0,
                            PurchaseDate = 20190521,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "iPhone",
                            CurrencyCountry = "Spain",
                            EndOfLife = 20211229,
                            Model = "8",
                            Price = 970.0,
                            PurchaseDate = 20181229,
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "iPhone",
                            CurrencyCountry = "Spain",
                            EndOfLife = 20230925,
                            Model = "11",
                            Price = 990.0,
                            PurchaseDate = 20200925,
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Motorola",
                            CurrencyCountry = "Sweden",
                            EndOfLife = 20230315,
                            Model = "Razr",
                            Price = 970.0,
                            PurchaseDate = 20200315,
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "iPhone",
                            CurrencyCountry = "Sweden",
                            EndOfLife = 20210715,
                            Model = "X",
                            Price = 1245.0,
                            PurchaseDate = 20180715,
                            Type = "Mobile"
                        });
                });

            modelBuilder.Entity("AssetTracking_2.Currency", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Shorten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Country");

                    b.ToTable("currencies");

                    b.HasData(
                        new
                        {
                            Country = "USA",
                            Rate = 1.0,
                            Shorten = "USD"
                        },
                        new
                        {
                            Country = "Sweden",
                            Rate = 9.9520999999999997,
                            Shorten = "SEK"
                        },
                        new
                        {
                            Country = "Spain",
                            Rate = 0.94869999999999999,
                            Shorten = "EUR"
                        },
                        new
                        {
                            Country = "Denmark",
                            Rate = 7.0784000000000002,
                            Shorten = "DKK"
                        },
                        new
                        {
                            Country = "Germany",
                            Rate = 0.94869999999999999,
                            Shorten = "EUR"
                        });
                });

            modelBuilder.Entity("AssetTracking_2.AssetItem", b =>
                {
                    b.HasOne("AssetTracking_2.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
